# -*- coding: utf-8 -*-
"""Unsupervised Anomaly Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10z_JWTenBYUdKkEAdfhbTNNqlplPcuMQ
"""

from sklearn.datasets import load_breast_cancer

pip install markupsafe==2.0.1

import jinja2
from pycaret.classification import *
from pycaret.anomaly import *

df = load_breast_cancer(as_frame=True)['data']
df_train = df.iloc[:-10]
df_unseen = df.tail(10)

anom = setup(data = df_train,
             silent = True)

models()

anom_model = create_model(model = 'iforest', fraction = 0.05)

results = assign_model(anom_model)

plot_model(anom_model, plot = 'tsne')

plot_model(anom_model, plot = 'umap')

save_model(model = anom_model, model_name = 'iforest_model')

loaded_model = load_model('iforest_model')
type(loaded_model)

loaded_model.predict(df_unseen)

loaded_model.predict_proba(df_unseen)

loaded_model.decision_function(df_unseen)

df_unseen.head()

"""Surse de inspiratie:

https://towardsdatascience.com/unsupervised-anomaly-detection-in-python-f2e61be17c2b

https://archive-beta.ics.uci.edu/ml/datasets/breast+cancer+wisconsin+diagnostic

https://www.kaggle.com/code/jorekai/exploration-and-classification

https://hands-on.cloud/implementing-anomaly-detection-using-python/
"""